# Generated by Django 4.1.4 on 2023-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lctec_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lctec_user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='lctec_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
