# Generated by Django 4.1.4 on 2023-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lctec_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lctec_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
