# Generated by Django 4.1.4 on 2023-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lctec_user', '0002_remove_lctec_user_is_admin_lctec_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lctec_user',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lctec_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lctec_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
