# Generated by Django 4.1.4 on 2023-02-28 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('statePref', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('order_created', models.DateTimeField(auto_now=True)),
                ('usd_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jpy_paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('stripe_token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_flp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jpy_flp_price', models.IntegerField(blank=True, default=0, null=True)),
                ('flp_quantity', models.IntegerField(default=1)),
                ('usd_track_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jpy_track_price', models.IntegerField(blank=True, default=0, null=True)),
                ('track_quantity', models.IntegerField(default=1)),
                ('flp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flps', to='flps_app.flp')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks_app.track')),
            ],
        ),
    ]
