# Generated by Django 4.1.4 on 2023-04-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Stripe Order (for FLPs and tracks)', 'verbose_name_plural': 'Stripe Orders (for FLPs and tracks)'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderflpitem',
            table='flp_orders',
        ),
        migrations.AlterModelTable(
            name='ordertrackitem',
            table='track_orders',
        ),
    ]
