# Generated by Django 4.1.4 on 2023-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='flp_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='track_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
