# Generated by Django 4.1.4 on 2023-03-02 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flps_app', '0001_initial'),
        ('order_app', '0003_orderflpitem_ordertrackitem_delete_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_order_created']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_created',
            new_name='date_order_created',
        ),
        migrations.RenameField(
            model_name='orderflpitem',
            old_name='jpy_flp_price',
            new_name='jpy_price',
        ),
        migrations.RemoveField(
            model_name='orderflpitem',
            name='flp_quantity',
        ),
        migrations.RemoveField(
            model_name='orderflpitem',
            name='usd_flp_price',
        ),
        migrations.AddField(
            model_name='orderflpitem',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderflpitem',
            name='flp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flps_app.flp'),
        ),
        migrations.AlterField(
            model_name='orderflpitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order'),
        ),
        migrations.DeleteModel(
            name='OrderTrackItem',
        ),
    ]
