# Generated by Django 4.1.4 on 2023-03-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_alter_orderflpitem_jpy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderflpitem',
            name='jpy_price',
        ),
        migrations.RemoveField(
            model_name='orderflpitem',
            name='usd_price',
        ),
        migrations.AddField(
            model_name='orderflpitem',
            name='date_order_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
