# Generated by Django 4.1.4 on 2023-03-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0001_initial'),
        ('order_app', '0006_remove_orderflpitem_jpy_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_order_created'], 'verbose_name': 'Stripe Order (for FLPs and tracks)', 'verbose_name_plural': 'Stripe Orders (for FLPs and tracks)'},
        ),
        migrations.AlterModelOptions(
            name='orderflpitem',
            options={'verbose_name': 'FLP Orders', 'verbose_name_plural': 'FLP Orders'},
        ),
        migrations.CreateModel(
            name='OrderTrackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order_created', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_items', to='order_app.order')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracks_app.track')),
            ],
            options={
                'verbose_name': 'Track Orders',
                'verbose_name_plural': 'Track Orders',
            },
        ),
    ]
