# Generated by Django 4.1.4 on 2023-03-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flps_app', '0001_initial'),
        ('tracks_app', '0001_initial'),
        ('order_app', '0007_alter_order_options_alter_orderflpitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderflpitem',
            name='flp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flp_items', to='flps_app.flp'),
        ),
        migrations.AlterField(
            model_name='orderflpitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flp_items', to='order_app.order'),
        ),
        migrations.AlterField(
            model_name='ordertrackitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_items', to='tracks_app.track'),
        ),
    ]
