# Generated by Django 4.1.4 on 2023-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_alter_orderflpitem_flp_alter_orderflpitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
