# Generated by Django 4.1.4 on 2023-03-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='purchase_count',
            new_name='downloads',
        ),
    ]
