# Generated by Django 4.1.4 on 2023-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0002_rename_purchase_count_track_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='jpy_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
