# Generated by Django 4.1.4 on 2023-03-30 05:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0003_alter_track_jpy_price_alter_track_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover_art',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=255, null=True, upload_to='cover_art'),
        ),
    ]
