# Generated by Django 4.1.4 on 2023-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0005_remove_track_cover_art_track_cover_art_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='flac_track',
            field=models.FileField(blank=True, null=True, upload_to='tracks'),
        ),
    ]
