# Generated by Django 4.1.4 on 2023-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks_app', '0006_track_flac_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='flac_track',
            field=models.FileField(blank=True, null=True, upload_to='flac_tracks'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(blank=True, null=True, upload_to='wav_tracks'),
        ),
    ]
