# Generated by Django 4.1.4 on 2023-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
