# Generated by Django 4.1.4 on 2023-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_track_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='song_dur',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
