# Generated by Django 4.1.4 on 2023-01-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_track_song_dur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flp_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('jpy_price', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField()),
                ('flp_zip', models.FileField(blank=True, null=True, upload_to='flp_zips')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('flp_is_free', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ('flp_name',),
            },
        ),
    ]
